// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package todo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTodoParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodoParams) Reset()         { *m = GetTodoParams{} }
func (m *GetTodoParams) String() string { return proto.CompactTextString(m) }
func (*GetTodoParams) ProtoMessage()    {}
func (*GetTodoParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *GetTodoParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodoParams.Unmarshal(m, b)
}
func (m *GetTodoParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodoParams.Marshal(b, m, deterministic)
}
func (m *GetTodoParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodoParams.Merge(m, src)
}
func (m *GetTodoParams) XXX_Size() int {
	return xxx_messageInfo_GetTodoParams.Size(m)
}
func (m *GetTodoParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodoParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodoParams proto.InternalMessageInfo

type AddTodoParams struct {
	Task                 string   `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTodoParams) Reset()         { *m = AddTodoParams{} }
func (m *AddTodoParams) String() string { return proto.CompactTextString(m) }
func (*AddTodoParams) ProtoMessage()    {}
func (*AddTodoParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *AddTodoParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTodoParams.Unmarshal(m, b)
}
func (m *AddTodoParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTodoParams.Marshal(b, m, deterministic)
}
func (m *AddTodoParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTodoParams.Merge(m, src)
}
func (m *AddTodoParams) XXX_Size() int {
	return xxx_messageInfo_AddTodoParams.Size(m)
}
func (m *AddTodoParams) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTodoParams.DiscardUnknown(m)
}

var xxx_messageInfo_AddTodoParams proto.InternalMessageInfo

func (m *AddTodoParams) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

type DelTodoParams struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelTodoParams) Reset()         { *m = DelTodoParams{} }
func (m *DelTodoParams) String() string { return proto.CompactTextString(m) }
func (*DelTodoParams) ProtoMessage()    {}
func (*DelTodoParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{2}
}

func (m *DelTodoParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelTodoParams.Unmarshal(m, b)
}
func (m *DelTodoParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelTodoParams.Marshal(b, m, deterministic)
}
func (m *DelTodoParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelTodoParams.Merge(m, src)
}
func (m *DelTodoParams) XXX_Size() int {
	return xxx_messageInfo_DelTodoParams.Size(m)
}
func (m *DelTodoParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DelTodoParams.DiscardUnknown(m)
}

var xxx_messageInfo_DelTodoParams proto.InternalMessageInfo

func (m *DelTodoParams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TodoObject struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Task                 string   `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoObject) Reset()         { *m = TodoObject{} }
func (m *TodoObject) String() string { return proto.CompactTextString(m) }
func (*TodoObject) ProtoMessage()    {}
func (*TodoObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{3}
}

func (m *TodoObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoObject.Unmarshal(m, b)
}
func (m *TodoObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoObject.Marshal(b, m, deterministic)
}
func (m *TodoObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoObject.Merge(m, src)
}
func (m *TodoObject) XXX_Size() int {
	return xxx_messageInfo_TodoObject.Size(m)
}
func (m *TodoObject) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoObject.DiscardUnknown(m)
}

var xxx_messageInfo_TodoObject proto.InternalMessageInfo

func (m *TodoObject) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TodoObject) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

type TodoResponse struct {
	Todos                []*TodoObject `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TodoResponse) Reset()         { *m = TodoResponse{} }
func (m *TodoResponse) String() string { return proto.CompactTextString(m) }
func (*TodoResponse) ProtoMessage()    {}
func (*TodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{4}
}

func (m *TodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoResponse.Unmarshal(m, b)
}
func (m *TodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoResponse.Marshal(b, m, deterministic)
}
func (m *TodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoResponse.Merge(m, src)
}
func (m *TodoResponse) XXX_Size() int {
	return xxx_messageInfo_TodoResponse.Size(m)
}
func (m *TodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TodoResponse proto.InternalMessageInfo

func (m *TodoResponse) GetTodos() []*TodoObject {
	if m != nil {
		return m.Todos
	}
	return nil
}

type DelResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelResponse) Reset()         { *m = DelResponse{} }
func (m *DelResponse) String() string { return proto.CompactTextString(m) }
func (*DelResponse) ProtoMessage()    {}
func (*DelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{5}
}

func (m *DelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelResponse.Unmarshal(m, b)
}
func (m *DelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelResponse.Marshal(b, m, deterministic)
}
func (m *DelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelResponse.Merge(m, src)
}
func (m *DelResponse) XXX_Size() int {
	return xxx_messageInfo_DelResponse.Size(m)
}
func (m *DelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelResponse proto.InternalMessageInfo

func (m *DelResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetTodoParams)(nil), "todo.getTodoParams")
	proto.RegisterType((*AddTodoParams)(nil), "todo.addTodoParams")
	proto.RegisterType((*DelTodoParams)(nil), "todo.delTodoParams")
	proto.RegisterType((*TodoObject)(nil), "todo.todoObject")
	proto.RegisterType((*TodoResponse)(nil), "todo.todoResponse")
	proto.RegisterType((*DelResponse)(nil), "todo.delResponse")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xdb, 0x4e, 0xc3, 0x30,
	0x0c, 0x86, 0xd7, 0x32, 0x88, 0x70, 0x29, 0x07, 0x73, 0x53, 0xf5, 0x86, 0x29, 0x48, 0xb0, 0xab,
	0x09, 0x75, 0x88, 0xd7, 0x00, 0x15, 0x5e, 0x20, 0x9b, 0xad, 0xa9, 0xb0, 0x91, 0xa9, 0x89, 0x78,
	0x2a, 0x1e, 0x12, 0xa5, 0x4d, 0x9a, 0x95, 0xdd, 0xc5, 0x87, 0xef, 0xff, 0x6d, 0x07, 0xc0, 0x6a,
	0xd2, 0x8b, 0x7d, 0xab, 0xad, 0xc6, 0xa9, 0x7b, 0xcb, 0x2b, 0xc8, 0x37, 0x6c, 0x3f, 0x34, 0xe9,
	0x37, 0xd5, 0xaa, 0x9d, 0x91, 0xf7, 0x90, 0x2b, 0xa2, 0x98, 0x40, 0x84, 0xa9, 0x55, 0xe6, 0xab,
	0x48, 0x66, 0xc9, 0xfc, 0xbc, 0xee, 0xde, 0xf2, 0x0e, 0x72, 0xe2, 0xed, 0x41, 0xd3, 0x25, 0xa4,
	0x0d, 0xf9, 0x96, 0xb4, 0x21, 0xf9, 0xd4, 0x5b, 0xbd, 0xae, 0x3e, 0x79, 0x6d, 0xff, 0x57, 0x07,
	0xc9, 0xf4, 0x40, 0xf2, 0x05, 0x2e, 0x1c, 0x51, 0xb3, 0xd9, 0xeb, 0x6f, 0xc3, 0xf8, 0x00, 0xa7,
	0x2e, 0x36, 0x45, 0x32, 0x3b, 0x99, 0x67, 0xd5, 0xf5, 0xa2, 0x1b, 0x3d, 0x8a, 0xd6, 0x7d, 0x59,
	0x3e, 0x42, 0x46, 0xbc, 0x1d, 0xb0, 0x02, 0xc4, 0x8e, 0x8d, 0x51, 0x1b, 0xf6, 0x7e, 0x21, 0xac,
	0x7e, 0x13, 0xc8, 0x1c, 0xf2, 0xce, 0xed, 0x4f, 0xb3, 0x66, 0xac, 0x40, 0xf8, 0x45, 0xf1, 0xb6,
	0x17, 0x1f, 0xed, 0x5d, 0x1e, 0x39, 0xca, 0x09, 0x2e, 0x41, 0xf8, 0xbd, 0x03, 0x33, 0x3a, 0x43,
	0x79, 0x33, 0x24, 0xc3, 0x40, 0x72, 0x82, 0xcf, 0x20, 0xfc, 0x89, 0x03, 0x34, 0xba, 0x78, 0x89,
	0xd1, 0x28, 0x52, 0xab, 0xb3, 0xee, 0x97, 0x96, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x52,
	0xe9, 0x87, 0xb3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoServiceClient interface {
	AddTodo(ctx context.Context, in *AddTodoParams, opts ...grpc.CallOption) (*TodoObject, error)
	DelTodo(ctx context.Context, in *DelTodoParams, opts ...grpc.CallOption) (*DelResponse, error)
	GetTodo(ctx context.Context, in *GetTodoParams, opts ...grpc.CallOption) (*TodoResponse, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) AddTodo(ctx context.Context, in *AddTodoParams, opts ...grpc.CallOption) (*TodoObject, error) {
	out := new(TodoObject)
	err := c.cc.Invoke(ctx, "/todo.todoService/addTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) DelTodo(ctx context.Context, in *DelTodoParams, opts ...grpc.CallOption) (*DelResponse, error) {
	out := new(DelResponse)
	err := c.cc.Invoke(ctx, "/todo.todoService/delTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) GetTodo(ctx context.Context, in *GetTodoParams, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := c.cc.Invoke(ctx, "/todo.todoService/getTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServiceServer is the server API for TodoService service.
type TodoServiceServer interface {
	AddTodo(context.Context, *AddTodoParams) (*TodoObject, error)
	DelTodo(context.Context, *DelTodoParams) (*DelResponse, error)
	GetTodo(context.Context, *GetTodoParams) (*TodoResponse, error)
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_AddTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTodoParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).AddTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.todoService/AddTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).AddTodo(ctx, req.(*AddTodoParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_DelTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelTodoParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).DelTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.todoService/DelTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).DelTodo(ctx, req.(*DelTodoParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_GetTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodoParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).GetTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.todoService/GetTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).GetTodo(ctx, req.(*GetTodoParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.todoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addTodo",
			Handler:    _TodoService_AddTodo_Handler,
		},
		{
			MethodName: "delTodo",
			Handler:    _TodoService_DelTodo_Handler,
		},
		{
			MethodName: "getTodo",
			Handler:    _TodoService_GetTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}
